#!/usr/bin/env python3
"""
gen-cache-properties.py — 为 DC 9.0.0 datafeed 目录生成 cache.properties

DC 9.0.0 的 NvdApiDataSource.getRemoteCacheProperties() 强制要求 datafeed
基础 URL 下存在 cache.properties，其中的 lastModifiedDate.* 时间戳使用
DateTimeFormatter 模式 uuuu-MM-dd'T'HH:mm:ssX 解析（单个 X 不接受 -04:00
形式的偏移），因此统一转换为 UTC 并以字面量 Z 结尾。

用法：python gen-cache-properties.py <mirror-dir>
从 <mirror-dir>/nvdcve-2.0-*.meta 读取 lastModifiedDate，输出 cache.properties。
"""
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def main() -> None:
    mirror = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    entries = {}
    for meta in sorted(mirror.glob("nvdcve-2.0-*.meta")):
        key = meta.stem.replace("nvdcve-2.0-", "")  # 2002..2026 / modified / recent
        text = meta.read_text(encoding="utf-8")
        m = re.search(r"lastModifiedDate:(\S+)", text)
        if not m:
            continue
        # 例：2026-07-15T03:00:09-04:00 → 2026-07-15T07:00:09Z（UTC，字面量 Z）
        dt = datetime.fromisoformat(m.group(1)).astimezone(timezone.utc)
        entries[key] = dt.strftime("%Y-%m-%dT%H:%M:%SZ")

    if "modified" not in entries:
        sys.exit("[!!] 缺少 nvdcve-2.0-modified.meta，无法生成 cache.properties")

    lines = [
        "# generated by gen-cache-properties.py — DC 9.0.0 datafeed cache metadata",
        "prefix=nvdcve-2.0-",
        f"lastModifiedDate={entries['modified']}",
    ]
    for key, ts in sorted(entries.items()):
        if key == "recent":
            continue  # DC 只使用年份与 modified 条目
        lines.append(f"lastModifiedDate.{key}={ts}")

    out = mirror / "cache.properties"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] {out} 已生成，共 {len(entries)} 个时间戳条目")


if __name__ == "__main__":
    main()
